### ISSUE TITLE
XLOG_INFO 打包上线时是不是得注释掉

### ISSUE THREAD

**Issue by yiimoney** [pcjbird/QuickTraceiOSLogger#1]
因为文件中没有类似
`#if DEBUG
#define XLOG_INFO (@__FILE__ ":" XLOG_LINE)
#else
#define XLOG_INFO nil
#endif`
这样的宏定义，这样意味着打包上线的时候需要将使用到XLOG_INFO都得注释掉

**Comment by pcjbird** [comment]
这取决于你的应用逻辑，你希望打出日志的话，就留着，另外XLFacility是支持设置日志等级的。
QuickTraceiOSLogger也不建议发布版本开启，你最好默认不开启，可以在设置里设置一个开关开启或关闭。
